### ISSUE TITLE
Update sensor fails

### ISSUE THREAD

**Issue by rgruyters** [xirixiz/home-assistant-config#5]
Since today I get the following errors for every sensor of mijnafvalwijzer:

```
Update for sensor.trash_gft fails

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/homeassistant/helpers/entity.py", line 221, in async_update_ha_state
    await self.async_device_update()
  File "/usr/local/lib/python3.6/site-packages/homeassistant/helpers/entity.py", line 349, in async_device_update
    await self.hass.async_add_executor_job(self.update)
  File "/usr/local/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/sensor/mijnafvalwijzer.py", line 135, in update
    for item in self.data.data:
TypeError: 'NoneType' object is not iterable
```

I'm running hassio version 0.87.1 on a PI3.

**Comment by xirixiz** [comment]
Fixed in release 2.0.7

**Comment by rgruyters** [comment]
Works. (for now)

Wouldn't be better to use the JSON output rather the html page? Everytime they change something in the HTML page, you have to update the sensor.

**Comment by xirixiz** [comment]
Correct, but I received an email from mijnafvalwijzer that it's not allowed to use json.mijnafvalwijze.nl. It's only for paying customers.

**Comment by Mariusthvdb** [comment]
issue is still alive though, so please don't close this, see:

https://community.home-assistant.io/t/garbage-pickup-date-mijnafvalwijzer-nl-custom-component/34631/210?u=mariusthvdb

sent a PM with address, hope it will be resolved anytime soon. Now have a constant flooding in the logs

**Comment by xirixiz** [comment]
I think I`m going to switch back to json anyway, scraping mijnafvalwijzer is way to messy. Fingers crossed mijnafvalwijzer won't complain again about this component. If so, I'll discontinue this component. Tomorrow evening I have all night to fix this!

**Comment by rgruyters** [comment]
I haven't check your Python code, but maybe increase the interval time. Once a day should be enough. (in mine opinion)
Maybe for the future split it up as component and sensor, that way you should be able to manually update the information.

> Once loaded, the speedtestdotnet component will expose a service (speedtestdotnet.speedtest) that can be called to run a Speedtest.net speed test on demand. This service takes no parameters. This can be useful if you have enabled manual mode.

https://www.home-assistant.io/components/speedtestdotnet/
